### PR TITLE
Replaced FileSaver with JSaver for windows support

### PR DESCRIPTION
**Pull request by Tamunorth**
This is a fix for #11

### CODE REVIEW

**Comment by JideGuru** [comment]
Sadly I currently do not own a Windows computer so I can't really review the windows part😢.
Please add a short video showing what you just fixed. Thanks

**Comment by Tamunorth** [comment]
https://user-images.githubusercontent.com/77057934/211215579-caa911e0-9ec8-4f95-81fc-a736ad33ef45.mp4

**Comment by Tamunorth** [comment]
@JideGuru Sorry i didn't respond earlier, I missed the mail from github, The app on the left is the current master branch, when export is tapped noting happens on windows, the one on the left actually works which is the fix.

**Comment by JideGuru** [comment]
@Tamunorth Really good work on the PR but I have some comments

the `JSaver` plugin doesn't seem to support MacOS
Screenshot 2023-01-08 at 22 13 29


But `file_saver` seems to support both Windows and MacOS.
Screenshot 2023-01-08 at 22 15 05

Perhaps we need to do a little config to allow file_saver to work on windows? or maybe we need to update the plugin? It'll be nice if you can help with this.

**Comment by JideGuru** [comment]
Closed as Stale

**Comment by ArchitMukherjee** [comment]
I am working on a Windows laptop and debugging on an Android emulator. Initially the drawing board was not getting saved, but I used `FileSaver.instance.saveAs(...)` instead of `FileSaver.instance.saveFile(...)` and it worked.

**Pull request closed without merging**
